[database]
container_name = "sunburst-mongo-primary"
test_db_name="test_db"
dev_db_name="dev_db"
prod_db_name="prod_db"

[database.local]
host="localhost"
port=20487
username="some_user"
password="some_pass"

[database.containerized]
host="sunburst-mongo-primary"
port=27017
username="some_user"
password="some_pass"

[scraper]
# osinfo placeholder for formatting. 
user_agent = "sunburst/0.1.0 ($osinfo)"
[scraper.profiles]
[scraper.profiles.tv2]
request_frequency_seconds = 108_000
