
# All passwords here should be gone and saved in secrets instead in production.

[database]
container_name = "sunburst-mongo-primary"
test_db_name = "test_db"
dev_db_name = "dev_db"
prod_db_name = "prod_db"

[database.local]
host = "localhost"
port = 20487
username = "some_user"
password = "some_pass"

[database.containerized]
host = "sunburst-mongo-primary"
port = 27017
username = "some_user"
password = "some_pass"

[cache]
container_name = "sunburst-redis-cache"
cached_common_article_search_terms = ["Ukraine", "Russia", "war"]
cached_sites = ["TV2"]
cache_common_articles_refresh_rate_seconds = 120

[cache.local]
host = "localhost"
port = 20489
password = "some-redis-pass"

[cache.containerized]
host = "sunburst-redis-cache"
port = 6379
password = "some-redis-pass"

[scraper]
# osinfo placeholder for formatting. 
user_agent = "sunburst/0.1.0 ($osinfo)"
[scraper.profiles]
[scraper.profiles.tv2]
request_frequency_seconds = 1_800
url = "https://tv2.dk/"

[distributor]
[distributor.dev]
host = "[::]"
port = 20488

[distributor.prod]
host = "0.0.0.0"
port = 20488

[distributor.containerized]
host = "sunburst-distributor"
port = 20488

[rest]
[rest.rs]
container_name = "sunburst-rs-rest"

[rest.rs.dev]
host = "127.0.0.1"
port = 22550

[rest.rs.prod]
host = "0.0.0.0"
port = 22550

[rest.rs.containerized]
host = "sunburst-rs-rest"
port = 22550

[rest.py]
container_name = "sunburst-py-rest"

[rest.py.dev]
host = "127.0.0.1"
port = 22551

[rest.py.prod]
host = "0.0.0.0"
port = 22551

[rest.py.containerized]
host = "sunburst-py-rest"
port = 22551

[rest.cs]
container_name = "sunburst-cs-rest"

[rest.cs.dev]
host = "127.0.0.1"
port = 22552

[rest.cs.prod]
host = "0.0.0.0"
port = 22552

[rest.cs.containerized]
host = "sunburst-cs-rest"
port = 22552

[rest.js]
container_name = "sunburst-js-rest"

[rest.js.dev]
host = "127.0.0.1"
port = 22553

[rest.js.prod]
host = "0.0.0.0"
port = 22553

[rest.js.containerized]
host = "sunburst-js-rest"
port = 22553

[rest.deno]
container_name = "sunburst-deno-rest"

[rest.deno.dev]
host = "127.0.0.1"
port = 22554

[rest.deno.prod]
host = "0.0.0.0"
port = 22554

[rest.deno.containerized]
host = "sunburst-deno-rest"
port = 22554