version: "3"

services:
  distributor:
    build: 
      context: "."
      dockerfile: distributor/Dockerfile
    image: mutestock/sunburst-distributor:latest

  rs_rest:
    build: 
      context: "."
      dockerfile: backend/rs_rest/Dockerfile
    image: mutestock/sunburst-rs-rest:latest
    
  py_rest:
    build: 
      context: "."
      dockerfile: backend/py_rest/Dockerfile
    image: mutestock/sunburst-py-rest:latest

  cs_rest:
    build:
      context: "."
      dockerfile: backend/cs_rest/Dockerfile
    image: mutestock/sunburst-cs-rest:latest
