version: "3"

services:
  database:
    container_name: "sunburst-mongo-primary"
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=some_user
      - MONGO_INITDB_ROOT_PASSWORD=some_pass
    ports:
      - 20487:27017
    volumes:
      - ./data:/data/db
    networks:
      - app-network

volumes:
  data:
    driver: local

networks:
  app-network:
    driver: "bridge"