version: "3"

services:
  database:
    container_name: "sunburst-mongo-primary"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=some_user
      - MONGO_INITDB_ROOT_PASSWORD=some_pass
    ports:
      - 20487:27017
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  cache:
    container_name: "sunburst-redis-cache"
    image: redis:latest
    ports:
      - 20489:6379
    command: redis-server --requirepass some-redis-pass
    networks:
      - app-network

  distributor:
    container_name: "sunburst-distributor"
    image: mutestock/sunburst-distributor:latest
    environment:
      - CONTAINERIZED=1
    ports:
      - 20488:20488
    networks:
      - app-network

  rs_rest:
    container_name: "sunburst-rs-rest"
    image: mutestock/sunburst-rs-rest:latest
    environment:
      - CONTAINERIZED=1
    ports:
      - 22550:22550
    networks:
      - app-network

  py_rest:
    container_name: "sunburst-py-rest"
    image: mutestock/sunburst-py-rest:latest
    environment:
      - CONTAINERIZED=1
    ports:
      - 22551:22551
    networks:
      - app-network

  cs_rest:
    container_name: "sunburst-cs-rest"
    image: mutestock/sunburst-cs-rest:latest
    environment:
      - CONTAINERIZED=1
    ports:
      - 22552:22552
    networks:
      - app-network

  js_rest:
    container_name: "sunburst-js-rest"
    image: mutestock/sunburst-js-rest:latest
    environment:
      - CONTAINERIZED=1
    ports:
      - 22553:22553
    networks:
      - app-network

volumes:
  data:
    driver: local

networks:
  app-network:
    driver: "bridge"
