version: "3"

services:
  database:
    container_name: "sunburst-mongo-primary"
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=some_user
      - MONGO_INITDB_ROOT_PASSWORD=some_pass
    ports:
      - 20487:27017
    volumes:
      - ./data:/data/db
    networks:
      - app-network

  cache:
    container_name: "sunburst-redis-cache"
    image: redis:latest
    restart: always
    ports:
      - 20489:6379
    command: redis-server --requirepass some-redis-pass
    networks:
      - app-network


volumes:
  data:
    driver: local

networks:
  app-network:
    driver: "bridge"
