version: "3"

services:
  distributor:
    build: 
      context: "."
      dockerfile: distributor/Dockerfile
    image: mutestock/sunburst-distributor:latest

  rs_rest:
    build: 
      context: "."
      dockerfile: backend/rs_rest/Dockerfile
    image: mutestock/sunburst-rs-rest:latest
    

