# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61sic.proto\x12\x05\x62\x61sic\"\x14\n\x12HealthCheckRequest\"\"\n\x13HealthCheckResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2V\n\x0c\x42\x61sicService\x12\x46\n\x0bHealthCheck\x12\x19.basic.HealthCheckRequest\x1a\x1a.basic.HealthCheckResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEALTHCHECKREQUEST._serialized_start=22
  _HEALTHCHECKREQUEST._serialized_end=42
  _HEALTHCHECKRESPONSE._serialized_start=44
  _HEALTHCHECKRESPONSE._serialized_end=78
  _BASICSERVICE._serialized_start=80
  _BASICSERVICE._serialized_end=166
# @@protoc_insertion_point(module_scope)
