name: 'Run integration tests'

on:
  push:
    branches:
      - main

jobs:
  run_interation_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
      - name: Add poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - name: Build python proto implementation package
        working-directory: ./proto-implementation
        run: | 
          poetry shell
          poetry update
          poetry build
          exit
      - name: Run tests
        working-directory: ./integration_tests
        run: |
          poetry shell
          poetry update
          chmod +x ./run_tests.sh
          ./run_tests.sh
