name: 'Run integration tests'

on:
  push:
    branches:
      - main

jobs:
  run_interation_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "docker-compose.yml"
      - name: Add poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - name: Build python proto implementation package
        working-directory: ./commons/py/proto_implementations
        run: | 
          poetry build
      - name: Run tests
        working-directory: ./integration_tests
        run: |
          poetry remove proto-implementations
          poetry add ../commons/py/proto_implementations/dist/proto_implementations-0.1.2.tar.gz
          poetry export > requirements.txt
          pip install -r requirements.txt
          chmod +x ./run_tests.sh
          ./run_tests.sh
