name: 'Run integration tests'

on:
  push:
    branches:
      - main

jobs:
  run_interation_tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: abatilo/actions-poetry@v2

      - name: Run tests
        working-directory: ./integration_tests
        run: |
          poetry shell
          poetry update
          chmod +x ./test_all.sh
          ./test_all.sh
